{% set name = "naif_eop_predict" %}
{% set version = "2024.8.28.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/naif_eop_predict-{{ version }}.tar.gz
  sha256: 158189903d7192e106589b40376dea8a2a8f0bb1fe03ff8c96dcc68b99fca8d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - naif_eop_predict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: NAIF Longterm Prediction Earth Orientation Parameters (EOP) Kernel for SPICE
  home: https://github.com/B612-Asteroid-Institute/naif_eop_predict
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akoumjian
    - moeyensj
    - ntellis
    - KatKiker
